########################################################################
# Minecraft Complex Server Operator for Container (MCSOC)
#
# Copyright (c) 2023-2026 kokoroq. All rights reserved.
#
#
#                    MCSOC remote host Config
#
#
#
#                                               VERSION: 1.1.0
########################################################################

# Remote host <IP address or FQDN>
REMOTE_HOST=""

# Remote user name
REMOTE_USER=""

# Path of SSH public key
SSHKEY_PUB=""

# Path of SSH private key
SSHKEY_PRIVATE=""

# SSH port
SSH_PORT="22"