########################################################################
# Minecraft Complex Server Operator for Container (MCSOC)
#
# Copyright (c) 2023-2026 kokoroq. All rights reserved.
#
#
#                       MCSOC Config
#
#
#
#                                               VERSION: 1.1.1
########################################################################

# Version
VERSION=1.1.1
